sudo: false
dist: trusty
language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache