version: '3'
services:
    app:
      build:
        context: ./
        dockerfile: Dockerfile.dev
      ports:
        - "80:80"
        - "443:443"
        - "9001:9001"
      volumes:
        - .:/var/www/html
      links:
        - db
      depends_on:
        - db
    db:
      image: mariadb:10.4
      volumes:
        - data_db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: adminpw
        MYSQL_DATABASE: shortr
        MYSQL_USER: shortener
        MYSQL_PASSWORD: changeme
volumes:
  data_db:
    driver: local