#!/bin/sh

#############
# environment
#############

set -e

# Set XDebug Host
if [ ${APP_ENV} == "dev" ]; then
  sed -e "s/^\(xdebug\.client_host\).*\$/\1 = ${DOCKERHOST}/" -i /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
fi