#!/bin/sh

#############
#  supervisor
#############

set -e

MYSQL_HOST=${MYSQL_HOST:-"db"}

if [ ${APP_ENV} == "dev" ]; then
    until nc -z -v -w30 ${MYSQL_HOST} 3306; do
        echo "Waiting for db ..."
        sleep 1
    done
    echo "Install dev environment"
    cd /var/www/html
    echo "Create database structure and seed some data"
    vendor/bin/phinx migrate -e dev
    vendor/bin/phinx seed:run -e dev
    echo "Run PHPUnit tests"
    vendor/bin/phpunit
fi