#!/bin/sh

##############
#  devtools
##############

set -ex

export CONFIG_DIR=/var/www/html/config

if [ ! -d ${CONFIG_DIR} ]; then
    mkdir ${CONFIG_DIR}
fi

if [ ! -f ${CONFIG_DIR}/settings.php ]; then
cat << EOF > ${CONFIG_DIR}/settings.php
<?php
return [
    'settings' => [
        // Slim Settings
        'determineRouteBeforeAppMiddleware' => false,
        'displayErrorDetails' => false,
        // Monolog settings
        'logger' => [
            'name' => 'app',
            'path' => __DIR__ . '/../log/app.log',
            'level' => \Monolog\Logger::DEBUG
        ],
        // DB settings
        'db' => [
            'driver' => 'mysql',
            'host' => 'db',
            'database' => 'shortr',
            'username' => 'shortener',
            'password' => 'changeme',
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],
        // App Settings
        'app' => [
            // Redirect to url if no slug set
            'defaultRedirect' => 'http://localhost',
            // Baseurl of shortener service
            'serviceUrl' => 'http://localhost',
            // Maximum request allowed to set shortr urls per hour
            'maxRequest' => '10',
            // JWT secret hash
            'jwtSecret' => 'your_jwt_secret_hash',
            // Lifetime of JWT token in seconds
            'jwtTokenLifetime' => 3600 * 24 * 15
        ]
    ]
];
EOF
fi

if [ -z "$JWT_SECRET" ]; then
    echo "[info] Generate JWT_SECRET token"
    export JWT_SECRET=$(tr -dc 'a-zA-Z0-9~!@#%^&*_()+}{?></";.,[]=-' < /dev/urandom | fold -w 32 | head -n 1)
fi

sed -i "s|'database'\s=>.*|'database' => '${MYSQL_DATABASE}',|" ${CONFIG_DIR}/settings.php
sed -i "s|'username'\s=>.*|'username' => '${MYSQL_USER}',|" ${CONFIG_DIR}/settings.php
sed -i "s|'password'\s=>.*|'password' => '${MYSQL_PASSWORD}',|" ${CONFIG_DIR}/settings.php
sed -i "s|'defaultRedirect'\s=>.*|'defaultRedirect' => '${REDIRECT_URL}',|" ${CONFIG_DIR}/settings.php
sed -i "s|'serviceUrl'\s=>.*|'serviceUrl' => '${SERVICE_URL}',|" ${CONFIG_DIR}/settings.php
sed -i "s|'jwtSecret'\s=>.*|'jwtSecret' => '${JWT_SECRET}',|" ${CONFIG_DIR}/settings.php